development:
  adapter: postgresql
  database: platform_development
  username: jasdeep
  password: 
  host: localhost
  port: 5432

test:
  adapter: postgresql
  database: platform_test
  username: jasdeep
  password: 
  host: localhost
  port: 5432

production:
  adapter: sqlite3
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
